# Generated by Django 3.1.2 on 2020-10-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='data',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='status',
            field=models.CharField(choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], db_index=True, default='PENDING', help_text='Current state of the task being run', max_length=50, verbose_name='Task State'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
