# Generated by Django 3.1.2 on 2020-10-13 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0002_auto_20201013_0113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pdf',
            new_name='Document',
        ),
    ]
