# Generated by Django 3.1.2 on 2020-10-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0003_auto_20201013_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.TextField(),
        ),
    ]
