# Generated by Django 3.1.2 on 2020-10-14 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0004_auto_20201013_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='task_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
